const languageSet = {
    english: {
      about: 'About',
      aboutMe: 'About Me',
      aboutMeBlurb: 'A Software developer proficient in JavaScript, Python and Java seeking positions in Front End/Full Stack Software Development. From Scotland but currently based in Niseko, Japan. A highly motivated software developer student, aiming to kickstart my career in a field that offers me the chance to be intellectually stimulated while continuing to develop my skills as a lifelong learner. Chronically curious and globally minded, my drive to better understand and experience the world has led me to spend the last 10 years living abroad - starting in New Zealand and now living long term in Japan. My desire to understand how things work first sparked my curiosity in software development, this then transformed from a desire to simply understand software to becoming a software developer myself. After 12 months of self-studying at home, I enrolled in CodeClan\'s Professional Software Development bootcamp in order to add more structure to my self taught learning. I am now seeking to transition into a career as a Software Developer.',
      contact: 'Contact',
      contactMe: 'Contact Me',
      font: 'font-playfair',
      formName: 'NAME',
      formNameTitle: 'Your Name',
      formEmail: 'EMAIL',
      formEmailTitle: 'Your Email',
      formMessage: 'MESSAGE',
      formMessageTitle: 'Your Message',
      formSubmit: 'SEND ME A MESSAGE',
      footer: 'A portfolio coded by:',
      hi: 'Hi, I\'m',
      hi2: 'A Junior Software Developer',
      home: 'Home',
      intro: 'I\'m a passionate and driven software developer, seeking opportunities to contribute to amazing dev teams while honing my development skills',
      lang: 'EN',
      nameFirst: 'James',
      nameLast: 'Robbins',
      projects: 'Projects',
      projectsSubtitle: 'Here are some of the projects I have been working on recently',
      projectGameTitle: 'Game Group Project',
      projectGameDescription: 'Built over the course of 14 days as a team of 4. We emulated a j-rpg style battle system with characters that we had created. A backend built using Java allowed the player to gain experience, find new weapons and attempt to battle the final boss!',
      technologiesTitle: 'Here are some of the technologies I have worked with recently:',
    },
    japanese: {
      about: '私について',
      aboutMe: '私について',
      aboutMeBlurb: 'JavaScript、Python、Javaに精通したソフトウェア開発者が、フロントエンド/フルスタックソフトウェア開発のポジションを募集しています。スコットランド出身で、現在は日本のニセコを拠点に活動しています。意欲的なソフトウェア開発者であり、生涯学習者としてのスキルを伸ばしながら、知的好奇心を刺激する分野でキャリアをスタートさせることを目指している。好奇心が旺盛でグローバルな思考を持つ私は、世界をよりよく理解し経験したいという欲求から、ニュージーランドを皮切りに過去10年間を海外で過ごし、現在は日本で長期にわたって生活しています。物事の仕組みを理解したいという思いから、ソフトウェア開発に興味を持つようになり、単にソフトウェアを理解したいという思いから、自らソフトウェア開発者になることを目指しました。12ヶ月間自宅で独学した後、独学で学んだことをさらに体系化するために、CodeClanのProfessional Software Development bootcampに入学しました。現在、ソフトウェア開発者としてのキャリアに移行することを目指しています。',
      contact: '連絡先',
      contactMe: '私に連絡',
      font: 'font-serifjp',
      formName: '名前',
      formNameTitle: 'お名前',
      formEmail: 'Eメール',
      formEmailTitle: 'お客様のメールアドレス',
      formMessage: 'メッセージ',
      formMessageTitle: 'お客様のメッセージ',
      formSubmit: 'メッセージで送る',
      footer: 'がコーディングしたポートフォリオ',
      hi: 'こんにちは、私は',
      hi2: 'ジュニアソフトウェア開発者です。',
      home: 'ホーム',
      intro: '私は情熱的で意欲的なソフトウェア開発者です。自分の開発スキルを磨きながら、素晴らしい開発チームに貢献する機会を求めています。',
      lang: 'JP',
      nameFirst: 'ジェームス',
      nameLast: 'ロビンズ',
      projects: 'プロジェクト',
      projectsSubtitle: '最近取り組んでいるプロジェクトを紹介します。',
      technologiesTitle: '最近、私が担当した技術を紹介します。',
    }
   }; 

export default languageSet;